# Generated by Django 2.0.4 on 2018-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhomepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('life', 'Life'), ('tech', 'Tech')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
