# Generated by Django 2.0.4 on 2018-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhomepage', '0002_auto_20180417_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Coding Life', (('django', 'Django'), ('scrapy', 'Scrapy'))), ('Enjoy Life', (('hangzhou', 'Hangzhou'), ('wenzhou', 'Wenzhou')))], max_length=20, null=True),
        ),
    ]
